site_name: AWS Certified Solutions Architect Notes
theme:
  name: material
  palette:
    primary: orange
    accent: amber
    icon:
      repo: fontawesome/brands/github  
repo_url: https://github.com/domi-nik-/aws-certified-solutions-architect-professional
repo_name: domi-nik-/aws-certified-solutions-architect-professional
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - def_list
plugins:
  - search
  - git-revision-date
